### ISSUE TITLE
Steps needed to return Clojurescript template

### ISSUE THREAD

**Issue by rome-user** [tauri-apps/awesome-tauri#138]
Hello, I am interested in using Tauri. But I learned that the template was unfortunately removed from `create-tauri-app`. I am wondering what changes need to be made in order to adapt the CLJS template so that a template can be submitted here.

I am not familiar with the changes in Tauri between create-tauri-app@v2 and the current Tauri. If the changes are large, then I would greatly appreciate some concrete steps needed to bring this back.

Thank you

**Comment by FabianLars** [comment]
It _should_ be enough to do `npm create tauri-app@2` to run the old create-tauri-app version.
Then you can use that to generate a tauri-clojurescript app which you can modify a bit to make it more template-ish.
Like if needed, make whatever you entered in the CTA prompts generic and obvious that they need to be changed and add a readme explaining how to use the template, and maybe some stuff to look out for like how the nextjs template does it: https://github.com/kvnxiao/tauri-nextjs-template#caveats.
