### ISSUE TITLE
Add modern-desktop-app-template

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/awesome-tauri#159]
I made https://github.com/elibroftw/modern-desktop-app-template which is react based, uses mantine, has custom titlebar,and best practices for publishing the app.

**Comment by FabianLars** [comment]
Looks really good to me! Feel free to open a PR :)

**Comment by simonhyll** [comment]
Closing this issue.
Please make a PR instead with a commit for the change you wish to see.
Cool project :)
