### ISSUE TITLE
About Checking IP address and port AWS command (AWSのポートの確認で使うコマンドについて）

### ISSUE THREAD

**Issue by SaniPerera** [tauri-apps/awesome-tauri#229]
I successfully executed the following two (sudo netstat -antup),( sudo ss -antup) commands used to check the aws port. But only one not succeed.
 It's about Isof command!

AWSのポートを確認する時に使う上記のコマンドを実行すると Isof 以外のコマンドは実行に成功するがIsof だけが成功しません！
なぜでしょうか

![WhatsApp画像 2023-10-25 20 47 06_dc042b8c](https://github.com/tauri-apps/awesome-tauri/assets/126953431/2f508e99-384e-4839-812e-962cc1a95336)

**Comment by FabianLars** [comment]
this is unrelated to tauri (and looks like spam to me?)

**Comment by SaniPerera** [comment]
Sorry for the inconvenience .I'm new one to GitHub and I'm still  learning how to use Issues.
