### ISSUE TITLE
Payload closed source -  There is no value in putting it in

### ISSUE THREAD

**Issue by xz1024** [tauri-apps/awesome-tauri#241]
It's a waste of time for me to download the software because it's not open source

**Comment by JonasKruckenberg** [comment]
As much as I love open source, the point of this list is only the show off *cool apps made with Tauri*, show what's possible and serve as inspiration.
The closed or open-sourcedness doesn't make a difference here, Payload is s cool app regardless.

If you feel the app should be made open source, feel free to make your case with the author themselves, their info is easy enough to find.
