### ISSUE TITLE
Add 2 more Awesome Tauri Projects

### ISSUE THREAD

**Issue by namanlp** [tauri-apps/awesome-tauri#258]
I found 2 more Awesome projects that use Tauri 🎉 

1. Guijs : https://github.com/Akryum/guijs
2. Jellyfin-vue : https://github.com/jellyfin/jellyfin-vue

They are really awesome projects and should be included in the list.

**Thank You**

**Comment by FabianLars** [comment]
Thanks for the suggestions!
Guijs was in our old list but it has been unmaintained for a long time now so i would rather not add it. jellyfin-vue looks cool though, so feel free to add it. We always appreciate PRs :)

**Comment by namanlp** [comment]
Yeah, I now I see that GuiJS is not updated for years.

Anyway, I made a PR for Jellyfin Vue

Thank You
