### ISSUE TITLE
New Tauri app: an IDE for coding and managing C4 model diagrams

### ISSUE THREAD

**Issue by keadex** [tauri-apps/awesome-tauri#288]
Hey team, I just released a beta version of Keadex Mina. It is a free, open source, serverless IDE for coding and managing C4 models diagrams:
 - [website](https://keadex.dev/en/projects/keadex-mina)
 - [github](https://github.com/keadex/keadex/tree/main/apps/keadex-mina)

It has also plugins for including interactive diagrams in Confluence, Docusaurus and React-based applications.

While the IDE is totally built with Tauri, the plugins are built by compiling to Wasm the Tauri/Rust code.

If you agree I'll be happy to open a PR for adding Keadex Mina to the Tauri apps list.

**Comment by FabianLars** [comment]
Awesome project! Yes a PR would be much appreciated :)

**Comment by keadex** [comment]
Here we go https://github.com/tauri-apps/awesome-tauri/pull/289
